name: Enforce Branch Naming Convention

on:
  pull_request:
    types: [opened]

jobs:
  branch-name-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME=$(echo ${{ github.ref }} | sed 's|refs/heads/||')
          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|chore)\/[a-z0-9-]+$ ]]; then
            echo "Invalid branch name: $BRANCH_NAME"
            echo "Branch names should follow the format: 'feature/branch-name', 'bugfix/branch-name', 'hotfix/branch-name', or 'chore/branch-name'."
            exit 1
          fi
