name: Validate Branch Name

on:
  pull_request:

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate branch name
        run: |
          branch_name=$(git rev-parse --abbrev-ref HEAD)

          # Allow main and develop branches
          if [[ "${branch_name}" == "main" || "${branch_name}" == "develop" ]]; then
            echo "Branch '${branch_name}' is exempt from validation."
            exit 0
          fi

          # Validate other branch names using a case statement
          case "${branch_name}" in
            feature/*|chore/*|test/*|fix/*)
              echo "Branch name '${branch_name}' is valid."
              ;;
            *)
              echo "Invalid branch name: ${branch_name}"
              echo "Branch names must start with 'feature/', 'chore/', 'test/', or 'fix/'"
              exit 1
              ;;
          esac
