name: Validate Branch Name

on:
  pull_request:

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate branch name
        run: |
          branch_name=$(git rev-parse --abbrev-ref HEAD)
          allowed_prefixes="feature|chore|test|fix"
          if [[ ! "${branch_name}" =~ ^(${allowed_prefixes})/ ]]; then
            echo "Invalid branch name: ${branch_name}"
            echo "Branch names must start with 'feature/', 'chore/', 'test/', or 'fix/'"
            exit 1
          fi
